import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        "en_US": {
          "fitnessApp": "Fitness App",
          "welcomeTitle": "Welcome",
          "welcomeSubtitle": "Join a happy and healthy world",
          "signIn": "SIGN IN",
          "signUp": "SIGN UP",
          "loginTitle": "Welcome back,",
          "loginSubTitle":
              "Step into a world of health and vitality with a simple login",
          "email": "Email",
          "password": "Password",
          "loginSuccessfulySubTitle": "User Logged in successfuly",
          "invalidEmailOrPassword": "Invalid Email or Password",
          "anErrorOccurred": "An error occurred",
          "ok": "Ok",
          "forgetPassword": "Forgete Password",
          "or": "OR ",
          "dontHaveAccount": "Don't have an Account? ",
          "signUpTitle": "Get On ",
          "signUpSubTitle":
              "Join our fitness community and start your transformation...",
          "fullName": "Full Name",
          "gender": "Gender",
          "birthDay": "Birth Day",
          "phoneNumber": "Phone Number",
          "aim": "Aim",
          "heigth": "Heigth",
          "weigth": "Weigth",
          "age": "Age",
          "actvityExtent": "Activity Extent",
          "alreadyHaveAnAccount": "Already have an Account? ",
          "register": "Register",
          "thisEmailIsAlreadyRegistered": "This email is already registered",
          "moreInfo": "More Info",
          "loose": "Loose",
          "gain": "Gain",
          "maintain": "Maintain",
          "pleaseSelectYourAim": "Please select your aim",
          "pleaseSelectYourExerciseLevel": "Please select your exerciseLevel",
          "pleaseSelectYourGender": "Please select your gender",
          "littleToNoExercise": "Little To No Exercise",
          "moderatelyActive": "Moderately Active",
          "veryActive": "Very Active",
          "registrationCompletedSuccessfully":
              "Registration Completed Successfully",
          "internalServerError": "Internal Server Error",
          "home": "Home",
          "noGym": "First join to gym",
          "gymName": "Gym Name",
          "monthlyPayment": "Monthly Payment",
          "location": "Location",
          "youHaveJoined": "You have joined",
          "failedToJoin": "Failed to join",
          "joinGym": "Join Gym",
          "pleaseTryAgain": "Please try again",
          "categories": "Categories",
          "findGym": "Find Gym",
          "gymList": "Gym List",
          "bestPlaceToFindGym": "Best Place To Find Gym",
          "gymLocation": "Gym Location",
          "birr": "Birr",
          "forYou": "For you",
          "viewMember": "View Member",
          "member": "Member",
          "join": "Join",
          "leave": "Leave",
          "aboutGym": "About Gym",
          "gymMember": "Gym Member",
          "post": "Post",
          "like": "Likes",
          "book": "Book",
          "recentlyAdded": "Recently Added",
          "author": "Author",
          "details": "Details",
          "search": "Search",
          "workout": "Workout",
          "workoutPlan": "Workout Plan",
          "exercise": "Exercise",
          "chooseExercise": "Choose Exercise",
          "profile": "Profile",
          "hello": "Hello",
          "protein": "Protein",
          "carbs": "Carbs",
          "fat": "Fat",
          "gramsNeeded": "Grams Needed",
          "mealForToday": "MEALS FOR TODAY",
          "foodList": "FOOD LIST",
          "updateProfile": "Update Profile",
          "update": "Update",
          "updatCompletedSuccessfully": "Updat completed successfully",
          "today": "Today",
          "addWorkoutPlan": "Add Workout",
          "chooseWorkout": "Choose Workout",
          "createWorkout": "Create Workout",
          "workoutCreated": "Workout with selected exercises created!",
          "workoutType": "Workout Type",
          "workoutList": "Workout List",
          "workoutNote": "Workout Note",
          "taskComplet": "Complet",
          "deleteWorkoutPlan": "Delete Workout Plan",
          "noWorkoutsFound": "No workouts found",
          "close": "Close",
          "easy": "Easy",
          "title": "Title",
          "startDate": "Start Time",
          "endDate": "End Time",
          "colors": "Colors",
          "cancel": "Cancel",
          "yourNextWorkout": "YOUR NEXT WORKOUT",
          "completed": "Completed",
          "todo": "TODO",
          "bmiTitle": "BMI CALCULATOR",
          "calculateBMI": "Calculate BMI",
          "setting": "Setting",
          "changeLanguage": "Change Language",
          "saveChanges": "Save Changes",
          "bodyFat": "Body Fat",
          "logout": "Logout",
          "yourResults": "Your results",
          "tryAgain": "TRY AGAIN",
          "bicepsExcercise": "Biceps Excercise",
          "bicepsExcercise1": "Biceps Excercis 1",
          "bicepsExcercise2": "Biceps Excercis 2",
          "bicepsExcercise3": "Biceps Excercis 3",
          "bicepsExcercise4": "Biceps Excercis 4",
          "chestExcercise": "Chest Excercise",
          "chestExcercise1": "Chest Excercise 1",
          "chestExcercise2": "Chest Excercise 2",
          "chestExcercise3": "Chest Excercise 3",
          "chestExcercise4": "Chest Excercise 4",
          "backExcercise": "Back Excercise",
          "backExcercise1": "Back Excercise 1",
          "backExcercise2": "Back Excercise 2",
          "backExcercise3": "Back Excercise 3",
          "backExcercise4": "Back Excercise 4",
          "shoulderExcercise": "Shoulder Excercise",
          "shoulderExcercise1": "Shoulder Excercise 1",
          "shoulderExcercise2": "Shoulder Excercise 2",
          "shoulderExcercise3": "Shoulder Excercise 3",
          "shoulderExcercise4": "Shoulder Excercise 4",
        },
        "et_ET": {
          "fitnessApp": "የአካል ብቃት መተግበሪያ",
          "welcomeTitle": "እንኳን ደህና መጡ",
          "welcomeSubtitle": "ወደ ደስተኛ እና ጤነኛ አለም ይቀላቀሉ",
          "signIn": " መግቢያ",
          "signUp": " ይመዝገቡ",
          "loginTitle": "እንኳን ደህና መጡ,",
          "loginSubTitle": "በቀላል ወደ ጤና እና ህይወት ዓለም ይግቡ",
          "email": "ኢሜይል",
          "password": "የይለፍ ቃል",
          "loginSuccessfulySubTitle": "በተሳካ ሁኔታ ገብተዋል።",
          "invalidEmailOrPassword": "የተሳሳተ ኢሜል ወይም የይለፍ ቃል ተጠቅመዋል",
          "anErrorOccurred": "ስህተት ተፈጥሯል",
          "ok": "እሺ",
          "forgetPassword": "የይለፍ ቃል ይሩሱ",
          "or": "ወይም",
          "dontHaveAccount": "መለያ የሎትም?",
          "signUpTitle": "ይመዝገቡ ",
          "signUpSubTitle": "የአካል ብቃት ማህበረሰባችንን ይቀላቀሉ እና ለውጥዎን ይጀምሩ።",
          "fullName": "ሙሉ ስም",
          "gender": "ጾታ",
          "birthDay": "የልደት ቀን",
          "phoneNumber": "ስልክ ቁጥር",
          "aim": "አላማ",
          "heigth": "ቁመት",
          "wigth": "ክብደት",
          "age": "ዕድሜ",
          "actvityExtent": "የተግባር መጠን",
          "alreadyHaveAnAccount": "መለያ አሎት? ",
          "register": "ይመዝገቡ",
          "thisEmailIsAlreadyRegistered": "ኢሜይሉ ከበፊቱም የተመዘገበ ነው",
          "moreInfo": "ተጨማሪ መረጃ",
          "loose": "ለመቀነስ",
          "gain": "ለመጨመር",
          "maintain": "ለማስጠበቅ",
          "pleaseSelectYourAim": "እባኮ አላማዎን ይምረጡ",
          "pleaseSelectYourExerciseLevel": "እባክዎ የእንቅስቃሴዎን ደረጃ ይምረጡ",
          "pleaseSelectYourGender": "እባክዎ ጾታዎን ይምረጡ",
          "littleToNoExercise": "ትንሽ እንቅስቃሴ",
          "moderatelyActive": "መጠነኛ ንቁ",
          "veryActive": "በጣም ከፍ ያለ",
          "registrationCompletedSuccessfully": "ምዝገባው በተሳካ ሁኔታ ተጠናቋል",
          "internalServerError": "የውስጥ መቆጣጠርያ ችግር",
          "home": "ዋና ገጽ",
          "noGym": "መጀመሪያ የጂም አባል ይሁኑ",
          "gymName": "የጂም ስም",
          "monthlyPayment": "ወርሃዊ ክፍያ",
          "location": "አካባቢ",
          "youHaveJoined": "በተሳካ ሁኔታ የጂሙ አባል ሆነዋል",
          "failedToJoin": "ይቅርታ የጂሙ አባል ለመሆን አልተሳካም",
          "joinGym": "ጂም ይቀላቀሉ",
          "pleaseTryAgain": "እባክዎ ደግመው ይሞክሩ",
          "categories": "ምድቦች",
          "findGym": "ጂም ፈልግ",
          "gymList": "የጂም ዝርዝር",
          "bestPlaceToFindGym": "አዲስ ጂም ለመፈለግ ጥሩ ቦታ",
          "gymLocation": "የጂሙ ቦታ",
          "birr": "ብር",
          "forYou": "አዲስ ነገር",
          "viewMember": "አባላቱን ለማየት",
          "member": "አባላት",
          "join": "አባል ለመሆን",
          "leave": "ለመልቀቅ",
          "aboutGym": "ስለ ጂሙ",
          "gymMember": "የጂሙ አባላት",
          "post": "ልጥፍ",
          "like": "የተወደዱ",
          "book": "መጽሐፍ",
          "recentlyAdded": "በቅርቡ የተጨመረ",
          "author": "ደራሲ",
          "details": "ዝርዝሮች",
          "search": "ፈልግ",
          "workout": "እንቅስቃሴ",
          "workoutPlan": "የአካል ብቃት እንቅስቃሴ እቅድ",
          "exercise": "የአካል ብቃት እንቅስቃሴ ",
          "profile": "መገለጫ",
          "hello": "ሰላም",
          "fat": "ስብ",
          "protein": "ፕሮቲን",
          "carbs": "ካርቦሃይድሬትስ",
          "gramsNeeded": "ግራም ያስፈልጋል",
          "mealForToday": "የዛሬ ምግቦች",
          "foodList": "የምግብ ዝርዝር",
          "updateProfile": "መገለጫ አዘምን",
          "update": "አዘምን",
          "updatCompletedSuccessfully": "ማዘመን በተሳካ ሁኔታ ተጠናቅቋል",
          "today": "ዛሬ",
          "addWorkoutPlan": "እንቅስቃሴን ይጨምሩ",
          "chooseExercise": "የአካል ብቃት እንቅስቃሴን ይምረጡ",
          "chooseWorkout": "የአካል ብቃት እንቅስቃሴን ይምረጡ",
          "createWorkout": "የአካል ብቃት እንቅስቃሴ ይፍጠሩ",
          "workoutType": "የአካል ብቃት እንቅስቃሴ ዓይነት",
          "workoutNote": "የአካል ብቃት እንቅስቃሴ ማስታወሻ",
          "workoutCreated": "በተመረጡ መልመጃዎች የአካል ብቃት እንቅስቃሴ ያድርጉ!",
          "workoutList": "የአካል ብቃት እንቅስቃሴ ዝርዝር",
          "taskComplet": "ተጠናቋል",
          "deleteWorkoutPlan": "የአካል ብቃት እንቅስቃሴ ዕቅድን ሰርዝ",
          "noWorkoutsFound": "ምንም የአካል ብቃት እንቅስቃሴዎች አልተገኙም።",
          "close": "ገጠመ",
          "easy": "ቀላል",
          "title": "ርዕስ",
          "startDate": "የመነሻ ጊዜ",
          "endDate": "የመጨረሻ ጊዜ",
          "colors": "ቀለሞች",
          "cancel": "ይቅር",
          "yourNextWorkout": "ቀጣዩ ስራዎ",
          "completed": "ተጠናቀቀ",
          "todo": "ለመስራት",
          "bmiTitle": "BMI ካልኩሌተር",
          "calculateBMI": "BMI አስላ",
          "bodyFat": "የሰውነት ስብ",
          "setting": "ማቀናበሪያ",
          "changeLanguage": "ቋንቋ መቀየሪያ",
          "saveChanges": "የተቀየረዉን አስቀምጥ",
          "logout": "መዉጫ",
          "yourResults": "የእርሶ ዉጤት",
          "tryAgain": "እንደገና ይሞክሩ",
          "bicepsExcercise": "የፊትእጅ ስራዎች",
          "bicepsExcercise1": "የፊትእጅ ስራ 1",
          "bicepsExcercise2": "የፊትእጅ ስራ 2",
          "bicepsExcercise3": "የፊትእጅ ስራ 3",
          "bicepsExcercise4": "የፊትእጅ ስራ 4",
          "chestExcercise": "የደረት ስራዎች",
          "chestExcercise1": "የደረት ስራ 1",
          "chestExcercise2": "የደረት ስራ 2",
          "chestExcercise3": "የደረት ስራ 3",
          "chestExcercise4": "የደረት ስራ 4",
          "backExcercise": "የኋላእጅ ስራዎች",
          "backExcercise1": "የኋላእጅ ስራ 1",
          "backExcercise2": "የኋላእጅ ስራ 2",
          "backExcercise3": "የኋላእጅ ስራ 3",
          "backExcercise4": "የኋላእጅ ስራ 4",
          "shoulderExcercise": "የትከሻ ስራወች",
          "shoulderExcercise1": "የትከሻ ስራ 1",
          "shoulderExcercise2": "የትከሻ ስራ 2",
          "shoulderExcercise3": "የትከሻ ስራ 3",
          "shoulderExcercise4": "የትከሻ ስራ 4",
          "legExcercise": "የእግር ስራዎች",
          "legExcercise1": "የእግር ስራ 1",
          "legExcercise2": "የእግር ስራ 2",
          "legExcercise3": "የእግር ስራ 3",
        },
        "et_OR": {
          "fitnessApp": "Appii fiitness",
          "welcomeTitle":
              "Kalaqa keessan tattaaffii guddachaa jiru irratti haa kaa'annu.",
          "signIn": "seena",
          "signUp": "galmaa'aa",
          "loginTitle": "Baga nagaan dhufte,",
          "loginSubTitle": "Addunyaa fayyaa fi jireenyaa salphaatti seeni",
          "email": "email",
          "password": "jecha iccitii",
          "loginSuccessfulySubTitle": "Loggin milkaa'inaan",
          "invalidEmailOrPassword": "Email ykn Password sirrii hin taane",
          "anErrorOccurred": "Dogoggorri uumame",
          "ok": "tole",
          "forgetPassword": "Jecha icciitii dagadhe",
          "or": "YOOKAAN",
          "dontHaveAccount": "Akkaawuntii hin qabduu?",
          "signUpTitle": "irra bu'aa ",
          "signUpSubTitle":
              "Hawaasa fiitness keenyatti makamaatii jijjiirama jalqabaa.",
          "fullName": "maqaa guutuu",
          "gender": "Koorniyaa",
          "birthDay": "guyyaa dhalootaa",
          "phoneNumber": "lakkoofsa bilbilaa",
          "aim": "Dhimma",
          "heigth": "Hojjaa",
          "wigth": "Ulfaatina",
          "age": "Umurii",
          "actvityExtent": "Guddina gochaa",
          "alreadyHaveAnAccount": "Akkaawuntii qabda? ",
          "register": "Galmeessuu",
          "thisEmailIsAlreadyRegistered": "Email kun duraan galmaa'ee jira",
          "moreInfo": "Odeeffannoo dabalataa",
          "loose": "Loose",
          "gain": "Argachuu",
          "maintain": "Tursuu",
          "pleaseSelectYourAim": "Kaayyoo Filadhaa",
          "pleaseSelectYourExerciseLevel": "Sadarkaa Shaakala Filadhaa",
          "pleaseSelectYourGender": " saala filadhu",
          "littleToNoExercise": "xiqqoo To Sochii Hin Qabu",
          "moderatelyActive": "giddu galeessaan Active",
          "veryActive": "baay'ee Active",
          "registrationCompletedSuccessfully":
              "Galmeen kun milkaa'inaan xumurameera",
          "internalServerError": "Dogoggora Sarvarii Keessaa",
          "home": "mana ",
          "noGym": "First join to gym",
          "gymName": "Maqaa Jiim",
          "monthlyPayment": "Kaffaltii Ji'aa",
          "location": "Bakka",
          "youHaveJoined": "makamtaniittu",
          "failedToJoin": "Itti makamuu hin dandeenye",
          "joinGym": "Jiim keessatti makamaa",
          "pleaseTryAgain": "irra deebi'ii ",
          "categories": "Ramaddiiwwan",
          "findGym": "Find Gym",
          "gymList": "Gym List",
          "bestPlaceToFindGym": "Best Place To Find Gym",
          "gymLocation": "Gym Location",
          "birr": "Birr",
          "forYou": "For you",
          "viewMember": "View Member",
          "member": "አባላት",
          "join": "Join",
          "leave": "Leave",
          "aboutGym": "About Gym",
          "gymMember": "Gym Member",
          "post": "Post",
          "like": "Like",
          "book": "kitaaba",
          "recentlyAdded": "Dhiheenya kana Dabalame",
          "author": "Barreessaa",
          "details": "Gadifageenyaan",
          "search": "Barbaaduu",
          "workoutPlan": "Karoora Sochii ",
          "exercise": "Shaakala ",
          "profile": "Ibsama",
          "hello": "Akkam",
          "protein": "Pirootiinii",
          "carbs": "Kaarboohayidireetii",
          "fat": "Furdaa",
          "gramsNeeded": "Grams Needed",
          "mealForToday": "Nyaata har'aa",
          "foodList": "Tarree nyaataa",
          "updateProfile": "Profaayila haaromsi",
          "update": "Odeeffannoo dhiyeenyaa",
          "updatCompletedSuccessfully": "Updat milkaa'inaan xumurame",
          "today": "Har'a",
          "addWorkoutPlan": "Qaamaa dabaluu",
          "chooseWorkout": "Shaakala filadhu",
          "createWorkout": "Shaakala uumi",
          "workout": "Workout",
          "workoutType": "Gosa sochii ",
          "workoutCreated": "Shaakala filatamoo uumaman waliin sochii!",
          "workoutList": "Tarree Sochii ",
          "workoutNote": "Hubachiisa Sochii",
          "taskComplet": "Hojii Xumuruu",
          "deleteWorkoutPlan": "Karoora Sochii Haquu",
          "noWorkoutsFound": "Sochii hin argamne",
          "close": "Cufuu",
          "easy": "Salphaa",
          "title": "Mata-duree",
          "startDate": "Yeroo ka'umsaa",
          "endDate": "Yeroo darbe",
          "colors": "Halluuwwan",
          "cancel": "Haquu",
          "yourNextWorkout": "SOCHII ITTI",
          "completed": "Xumurameera",
          "todo": "HOJJECHUUF",
          "bmiTitle": "Shallaggii BMI",
          "calculateBMI": "BMI shallagi",
          "bodyFat": "Copha qaamaa",
          "setting": "Setting up gochuu",
          "saveChanges": "Save Changes",
          "changeLanguage": "Change Language",
          "logout": "Ba'i",
          "yourResults": "Your results",
          "tryAgain": "TRY AGAIN",
          "bicepsExcercise": "Biceps Excercise",
          "bicepsExcercise1": "Biceps Excercis 1",
          "bicepsExcercise2": "Biceps Excercis 2",
          "bicepsExcercise3": "Biceps Excercis 3",
          "bicepsExcercise4": "Biceps Excercis 4",
          "chestExcercise": "Chest Excercise",
          "chestExcercise1": "Chest Excercise 1",
          "chestExcercise2": "Chest Excercise 2",
          "chestExcercise3": "Chest Excercise 3",
          "chestExcercise4": "Chest Excercise 4",
          "backExcercise": "Back Excercise",
          "backExcercise1": "Back Excercise 1",
          "backExcercise2": "Back Excercise 2",
          "backExcercise3": "Back Excercise 3",
          "backExcercise4": "Back Excercise 4",
          "shoulderExcercise": "Shoulder Excercise",
          "shoulderExcercise1": "Shoulder Excercise 1",
          "shoulderExcercise2": "Shoulder Excercise 2",
          "shoulderExcercise3": "Shoulder Excercise 3",
          "shoulderExcercise4": "Shoulder Excercise 4",
          "legExcercise": "Leg Excercise",
          "legExcercise1": "Leg Excercise 1",
          "legExcercise2": "Leg Excercise 2",
          "legExcercise3": "Leg Excercise 3",
          "legExcercise4": "Leg Excercise 4",
        },
        "et_TG": {
          "fitnessApp": "ናይ ብቕዓት ኣፕ",
          "welcomeTitle": "ፈጠራኻ ኣብ ፈተና ምዕባይ ነእትዎ።",
          "signIn": "ኣብ ውሽጢ ምእታው",
          "signUp": "ተመዝገቡ",
          "loginTitle": "እንኳዕ ደሓን መፁ,",
          "loginSubTitle": "ናብ ዓለም ጥዕናን ህይወትን ብቐሊሉ እቶ",
          "email": "ኢመይል",
          "password": "መሕለፊ ቓል",
          "loginSuccessfulySubTitle": "መእተዊ ብዓወት",
          "invalidEmailOrPassword": "ዘይሕጋዊ ኢመይል ወይ ፓስዎርድ",
          "anErrorOccurred": "ጌጋ ኣጋጢሙ",
          "ok": "ደሓን",
          "forgetPassword": "ፓስዎርድ ረሲዐዮ",
          "or": "ወይ",
          "dontHaveAccount": "ኣካውንት የብልካን?",
          "signUpTitle": "ተሰቐል ",
          "signUpSubTitle": "ኣብ ማሕበረሰብ ብቕዓትና ተጸንበሩ እሞ ለውጥኹም ጀምሩ",
          "fullName": "ምሉእ ስም",
          "gender": "ፆታ",
          "birthDay": "በዓል ልደት",
          "phoneNumber": "ቁጽሪ ተሌፎን",
          "aim": "ዕላማ",
          "heigth": "ቁመት",
          "wigth": "ክብደት",
          "age": "ዕድመ",
          "actvityExtent": "መጠን ተግባር",
          "alreadyHaveAnAccount": "ኣካውንት ኣለካ ድዩ? ",
          "register": "ምዝገባ",
          "thisEmailIsAlreadyRegistered": "እዚ ኢመይል ድሮ ተመዝጊቡ ኣሎ",
          "moreInfo": "ተወሳኺ ሓበሬታ",
          "loose": "ልሕሉሕ",
          "gain": "ርኸብ",
          "maintain": "ምዕቃብ",
          "pleaseSelectYourAim": "እባኮ አላማዎን ይምረጡ",
          "pleaseSelectYourExerciseLevel": "እባክዎ የእንቅስቃሴዎን ደረጃ ይምረጡ",
          "pleaseSelectYourGender": "በጃኹም ጾታኹም ምረጹ",
          "littleToNoExercise": "ትንሽ እንቅስቃሴ",
          "moderatelyActive": "መጠነኛ ንቁ",
          "veryActive": "በጣም ከፍ ያለ",
          "registrationCompletedSuccessfully": "እቲ ምዝገባ ብዓወት ተዛዚሙ ኣሎ።",
          "internalServerError": "ውሽጣዊ ኣገልጋሊ ጌጋ",
          "home": "ኣብ ገዛ",
          "noGym": "First join to gym",
          "gymName": "ስም ጂምናዝየም",
          "monthlyPayment": "ወርሓዊ ክፍሊት",
          "location": "ኣንፈት",
          "youHaveJoined": "ተጸንቢርኩም ኣለኹም",
          "failedToJoin": "ክጽንበር ኣይከኣለን",
          "joinGym": "ናብ ጂምናዝየም ተጸንበሩ",
          "pleaseTryAgain": "በጃኹም ደጊምኩም ፈትኑ",
          "categories": "ምድባት",
          "findGym": "Find Gym",
          "gymList": "Gym List",
          "bestPlaceToFindGym": "Best Place To Find Gym",
          "gymLocation": "Gym Location",
          "birr": "Birr",
          "forYou": "For you",
          "viewMember": "View Member",
          "member": "አባላት",
          "join": "Join",
          "leave": "Leave",
          "aboutGym": "About Gym",
          "gymMember": "Gym Member",
          "post": "Post",
          "like": "Likes",
          "book": "መፅሓፍ",
          "recentlyAdded": "ኣብ ቀረባ እዋን ዝተወሰኸ",
          "author": "ጸሓፊ",
          "details": "ዝርዝራት",
          "search": "ምድላይ",
          "workout": "Workout",
          "workoutPlan": "ውጥን ስፖርታዊ ምንቅስቓስ",
          "exercise": "ልምምድ ",
          "profile": "መግለፂ",
          "hello": "ሰላም",
          "protein": "ፕሮቲን",
          "carbs": "ካርቦሃይድሬት",
          "fat": "ረጒድ",
          "gramsNeeded": "ግራም የድሊ",
          "mealForToday": "ናይ ሎሚ መግቢ",
          "foodList": "ዝርዝር መግቢ",
          "updateProfile": "ፕሮፋይል ኣዘምንዎ።",
          "update": "ኣዘምን",
          "updatCompletedSuccessfully": "Updat ብዓወት ተዛዚሙ",
          "today": "ሎምዓንቲ",
          "addWorkoutPlan": "ኣካላዊ ምንቅስቓስ ምውሳኽ",
          "chooseWorkout": "ሓደ ልምምድ ምረጽ",
          "createWorkout": "ልምምድ ምፍጣር",
          "workoutType": "ዓይነት ምንቅስቓስ ኣካላት",
          "workoutCreated": "ስፖርታዊ ምንቅስቓስ ምስ ዝተመርጹ ምውስዋስ ኣካላት ተፈጢሩ!",
          "workoutList": "ዝርዝር ስፖርታዊ ምንቅስቓስ",
          "workoutNote": "ስፖርታዊ ምንቅስቓስ መተሓሳሰቢ",
          "noWorkoutsFound": "ስፖርታዊ ምንቅስቓስ ኣይተረኽበን።",
          "taskComplet": "ዕማም ምዝዛም",
          "deleteWorkoutPlan": "ውጥን ስፖርታዊ ምንቅስቓስ ምድምሳስ",
          "close": "ዕፁው",
          "easy": "ቀሊል",
          "title": "ርእሲ",
          "startDate": "ናይ ምብጋስ ግዜ",
          "endDate": "ዝሓለፈ ግዜ",
          "colors": "ሕብርታት",
          "cancel": "ይቅር",
          "yourNextWorkout": "ዝቕጽል ስፖርታዊ ምንቅስቓስካ",
          "completed": "ተዛዚሙ",
          "todo": "ክትገብሮ ዘለካ",
          "bmiTitle": "BMI ካልኩሌተር",
          "calculateBMI": "BMI ኣስልጥ",
          "bodyFat": "ስብሒ ኣካላት",
          "setting": "ምድላው",
          "changeLanguage": "Change Language",
          "saveChanges": "Save Changes",
          "logout": "ውጹ",
          "yourResults": "Your results",
          "tryAgain": "TRY AGAIN",
          "bicepsExcercise": "የፊትእጅ ስራዎች",
          "bicepsExcercise1": "የፊትእጅ ስራ 1",
          "bicepsExcercise2": "የፊትእጅ ስራ 2",
          "bicepsExcercise3": "የፊትእጅ ስራ 3",
          "bicepsExcercise4": "የፊትእጅ ስራ 4",
          "chestExcercise": "የደረት ስራዎች",
          "chestExcercise1": "የደረት ስራ 1",
          "chestExcercise2": "የደረት ስራ 2",
          "chestExcercise3": "የደረት ስራ 3",
          "chestExcercise4": "የደረት ስራ 4",
          "backExcercise": "የኋላእጅ ስራዎች",
          "backExcercise1": "የኋላእጅ ስራ 1",
          "backExcercise2": "የኋላእጅ ስራ 2",
          "backExcercise3": "የኋላእጅ ስራ 3",
          "backExcercise4": "የኋላእጅ ስራ 4",
          "shoulderExcercise": "የትከሻ ስራወች",
          "shoulderExcercise1": "የትከሻ ስራ 1",
          "shoulderExcercise2": "የትከሻ ስራ 2",
          "shoulderExcercise3": "የትከሻ ስራ 3",
          "shoulderExcercise4": "የትከሻ ስራ 4",
          "legExcercise": "የእግር ስራዎች",
          "legExcercise1": "የእግር ስራ 1",
          "legExcercise2": "የእግር ስራ 2",
          "legExcercise3": "የእግር ስራ 3",
        },
      };
}
